# Generated by Django 3.1.5 on 2021-07-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210708_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(max_length=4)),
                ('comment_by', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(max_length=10000),
        ),
    ]
