# Generated by Django 3.1.5 on 2021-07-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210720_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
