# Generated by Django 3.2.9 on 2021-11-29 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.ManyToManyField(default=0, related_name='post_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
